# config.py or similar file
SCALE_FACTOR = 1  # or 2 for doubling the size
ORIGINAL_WIDTH = 640
ORIGINAL_HEIGHT = 480
SCALED_WIDTH = int(ORIGINAL_WIDTH * SCALE_FACTOR)
SCALED_HEIGHT = int(ORIGINAL_HEIGHT * SCALE_FACTOR)
